# HW 03 - Part 2: Data Exploration

---
---
**DISCLAIMER: This is a fake story, not a real incident! We have created this story just for the data exploration purpose.**

---
---

**Campus Police Department**

Incident Report

---

**Incident Date:** September 10, 2025

**Location of Incident:** 2nd Floor, Iribe Building

**Items Left at the Scene:** Red Ticket for Zichao's Magic Show

**Case Number:** 2025-IRB-0027

---
**Victim Information:**

**Name:** Dr. Fardina Alam

**Affiliation:** University of Maryland, College Park

**Position:** Professor

**Contact Information:** fardina@umd.edu

---

**Incident Description:**

On the evening of September 10, 2025, an unknown individual(s) unlawfully entered Dr. Fardina's room located on the 2nd floor of Iribe and stole a set of Markers. The stolen items were a set of limited edition markers that Dr. Fardina had spent years collecting. At the scene of the crime, a red entry ticket for "Zichao's Magic Show" was found on the floor near Dr. Fardina's desk.

In [1]:
# We import all essential libraries for this HW; if you want to add additional libraries, you can add more here!
import pandas as pd
from datetime import datetime

## Instructions:

In this assignment, you are tasked with solving the mystery of Dr. Fardina's stolen markers and finding the culprit.

* To accomplish this, you will be provided with **4 data sets** containing key information related to the incident. The list of the data sets name given below:

 - Profiles
 - Witnesses
 - Zichao's magic show
 - Interrogation Statements



* Your goal is to analyze these data sets to uncover the clues and evidences that will lead you to the thief.

**Be careful in following instructions as it may lead to you losing points :(**

Take a moment to look at all the data sets below:

---

**Profiles:**

This dataset contains information regarding all the potential people that could have committed the crime. General information regarding each person are as follows:
- **ID:** A **unique** identification for each person
- **Name:** The name of the person
- **Birthday:** The birthday of the person
- **Location_during_crime:** The location of the person during the crime
- **Eye_Color:** The eye color of the person
- **Skin_Color:** The skin color of the person
- **Hair_Color:** The hair color of the person
- **Height:** The height of the person in cm

**Witnesses:**

This dataset contains a statement from everyone in profiles, regarding suspicious things they saw during the time of the crime. Information that comes in this dataset are as follows:
- **ID:** A **Unique** identification for each person
- **Statement:** A statement from the person regarding a suspicious activity during the time of the crime

**Zichao's magic show:**

This dataset contains everyone that purchased a ticket for the show. **NOTE** that not everyone in profiles has purchased a ticket for this show. The Information contained in this dataset are as follows:
- **ID:** A **Unique** indentification for each person
- **Ticket_Number:** A **Unique** number that serves as an identification for the ticket bought

**Interrogation Statements:**

This datasets contains a statement from each person after they have been interrogated. **NOTE** assume that each statement is 100% true and that there are people who aren't in "Profiles" in this dataset. The Information contained in this dataset are as follows:

- **Name:** The name of the person being interrogated
- **Statement:** A statement the person gives after being interrogated

---

## Instructions for the Students:

In this assignment, you are tasked with solving the mystery of Dr. Fardina's stolen markers and finding the culprit.

* To accomplish this, you will be provided with **4 data sets** containing key information related to the incident. The list of the data sets name given below:

 - Profiles
 - Witnesses
 - Zichao's magic show
 - Interrogation Statements



* Your goal is to analyze these data sets to uncover the clues and evidences that will lead you to the thief.

**Be careful in following instructions as it may lead to you losing points :(**

Take a moment to look at summary of all the data sets below:

---

**Profiles:**

This dataset contains information regarding all the potential people that could have committed the crime.

**Witnesses:**

This dataset contains a statement from everyone in profiles, regarding suspicious things they saw during the time of the crime.

**Zichao's magic show:**

This dataset contains everyone that purchased a ticket for the show. **NOTE** that not everyone in profiles has purchased a ticket for this show. In this dataset, there is a column named  **"Ticket_Number"** which is an **Unique** number that serves as an identification for the ticket bought.

**Interrogation Statements:**

This datasets contains a statement from each person after they have been interrogated. **NOTE** assume that each statement is 100% true and that there are people who aren't in "Profiles" in this dataset.

---

## Q1) Lets begin by observing the profiles dataset


**TASK 1.1 (1 Point):**  In the code box below, load in "Profiles" dataset into a variable called **profiles_df** and display it

In [2]:
# Write your code here
profiles_df = pd.read_csv("data/Profiles.csv")
profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height
0,P299,James Mason,1968/07/10,fourth floor,red,indigo,orange,191
1,P086,Christopher Rodriguez,1978/03/10,second floor,indigo,indigo,green,198
2,P022,Misty Ashley,1989/10/08,fourth floor,blue,red,violet,154
3,P003,Amanda Brown,1995/27/10,lobby,green,blue,violet,158
4,P036,William Jones,1990/26/02,fourth floor,blue,yellow,orange,184
...,...,...,...,...,...,...,...,...
343,P126,Kenneth Watson,1987/03/01,NaN,violet,indigo,red,176
344,P203,Donald Anderson,1964/26/09,third floor,yellow,indigo,orange,193
345,P273,Harold Watkins,2002/12/07,fourth floor,blue,indigo,red,193
346,P290,Brandon Bennett,10/03/1993,third floor,NaN,yellow,indigo,161
347,P233,Karen Lambert,06/27/1981,second floor,red,yellow,orange,169

**TASK 1.2 (1 Point):**  Next, you need to display the number of rows and columns in the "Profiles" dataset.

In [3]:
# Write your code here
profiles_df.shape

(348, 8)

**TASK 1.3 (1 Point):**  Next, you need to display the name of the columns in the "Profiles" dataset.

In [4]:
# Write your code here
profiles_df.columns.tolist()

['ID',
 'Name',
 'Birthday',
 'Location_during_crime',
 'Eye_Color',
 'Skin_Color',
 'Hair_Color',
 'Height']

**TASK 1.4 (1 Point):**  Now, you need to display the types of the columns in the "Profiles" dataset.

In [5]:
# Write your code here
profiles_df.dtypes

ID                         str
Name                       str
Birthday                   str
Location_during_crime      str
Eye_Color                  str
Skin_Color                 str
Hair_Color                 str
Height                   int64
dtype: object

**TASK 1.5 (2 Points):** Utilizing the .count() function on this dataset and set it to the variable **info** and then display it. Write any **potential problem** that you see with the dataset when observing the output of the count function:

In [6]:
# Write your code here
info = profiles_df.count()
info

ID                       348
Name                     348
Birthday                 348
Location_during_crime    280
Eye_Color                280
Skin_Color               348
Hair_Color               348
Height                   348
dtype: int64

*Write your observations here:* Dataset contains 348 rows, Location_during_crime and Eye_color are short some values, they only have 280 non-null values meaning it has 68 missing values.

**TASK 1.6 (4 Points):** Look back at the "Profiles" dataset. Using other pandas functions than count(), can you spot another potential problem with the dataset?

In [7]:
# Write your code here
print("Duplicate rows:", profiles_df.duplicated().sum())

Duplicate rows: 48

*Write your observation here:*  The dataset contains 48 missing values. They should be removed to maintain consistency and avoid counting the same row twice.

## Q2) Cleaning the data set

**TASK 2.1 (10 Points):** Lets begin by fixing the Birthday column. You may notice that the dates are in inconsistent format!

- Pandas internally represent dates in 'datetime64' format which is a form of ISO 8601. Basically, dates are represented as yyyy-mm-dd.


- Fix all the dates in the Birthday Column.
- Display the "Profiles" dataframe after you are done.
- Note that the only 2 formats the dates are in is either yyyy/dd/mm or mm/dd/yyyy, you want to represent them as yyyy-mm-dd


**HINT:** some datetime functions might make things easier.
- https://www.geeksforgeeks.org/python-pandas-to_datetime/
- https://www.programiz.com/python-programming/datetime/strftime

In [8]:
# Your Code here

profiles_df = profiles_df.drop_duplicates().reset_index(drop=True)

def fix_date(date):
    date_parts = date.split("/")

    if len(date_parts[0]) == 4:
        # for yyyy/dd/mm
        return datetime(
            int(date_parts[0]),
            int(date_parts[2]),
            int(date_parts[1])
        )
    else:
        # for mm/dd/yyyy
        return datetime(
            int(date_parts[2]),
            int(date_parts[0]),
            int(date_parts[1])
        )

profiles_df["Birthday"] = pd.to_datetime(
    profiles_df["Birthday"].apply(fix_date)
)

profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height
0,P299,James Mason,1968-10-07,fourth floor,red,indigo,orange,191
1,P086,Christopher Rodriguez,1978-10-03,second floor,indigo,indigo,green,198
2,P022,Misty Ashley,1989-08-10,fourth floor,blue,red,violet,154
3,P003,Amanda Brown,1995-10-27,lobby,green,blue,violet,158
4,P036,William Jones,1990-02-26,fourth floor,blue,yellow,orange,184
...,...,...,...,...,...,...,...,...
295,P218,Shannon Abbott,1987-08-14,fourth floor,green,green,blue,182
296,P126,Kenneth Watson,1987-01-03,NaN,violet,indigo,red,176
297,P203,Donald Anderson,1964-09-26,third floor,yellow,indigo,orange,193
298,P273,Harold Watkins,2002-07-12,fourth floor,blue,indigo,red,193
299,P233,Karen Lambert,1981-06-27,second floor,red,yellow,orange,169

**TASK 2.2 (5 Points):** Now that we have cleaned up the Birthday column, lets find the age of each person. Create a new column called "Age" that displays the age of the person **on the day of the crime.** Once you are done, display the
"Profiles" dataframe

In [9]:
# Write your code here

crime_date = pd.Timestamp("2025-09-10")

profiles_df["Age"] = (
    crime_date.year - profiles_df["Birthday"].dt.year
    - (
        (profiles_df["Birthday"].dt.month > crime_date.month)
        | (
            (profiles_df["Birthday"].dt.month == crime_date.month)
            & (profiles_df["Birthday"].dt.day > crime_date.day)
        )
    ).astype(int)
)

profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age
0,P299,James Mason,1968-10-07,fourth floor,red,indigo,orange,191,56
1,P086,Christopher Rodriguez,1978-10-03,second floor,indigo,indigo,green,198,46
2,P022,Misty Ashley,1989-08-10,fourth floor,blue,red,violet,154,36
3,P003,Amanda Brown,1995-10-27,lobby,green,blue,violet,158,29
4,P036,William Jones,1990-02-26,fourth floor,blue,yellow,orange,184,35
...,...,...,...,...,...,...,...,...,...
295,P218,Shannon Abbott,1987-08-14,fourth floor,green,green,blue,182,38
296,P126,Kenneth Watson,1987-01-03,NaN,violet,indigo,red,176,38
297,P203,Donald Anderson,1964-09-26,third floor,yellow,indigo,orange,193,60
298,P273,Harold Watkins,2002-07-12,fourth floor,blue,indigo,red,193,23
299,P233,Karen Lambert,1981-06-27,second floor,red,yellow,orange,169,44

**TASK 2.3 (10 Points):** Now that we have created the "age"; lets clean the 'Eye_color's column.

***Please read the directions carefully:***


- In order to fill in the missing eye_colors, we want to find the **most common eye_color** among those who have the **same hair and skin color**.
- For Instance, if we want to find the eye_color of someone who has yellow hair and violet skin:
 - we would first find everything who has the same hair and skin color, in this case it would be yellow hair and violet skin
 - and then we find the most common eye_color among them.
 - we then replace the missing eye_color with the eye color that is the most common among the people with the same hair and skin color.
- Watch out for redundant data!

- ***FIX: In the case that you find multiple modes, choose the color that appears first in alphabetical order***

 When you finish filling in the missing eye colors, please display the profiles_df

In [10]:
# Write your code here

mode_map = (
    profiles_df.dropna(subset=["Eye_Color"])
    .groupby(["Hair_Color", "Skin_Color"])["Eye_Color"]
    .agg(lambda x: sorted(x.mode())[0])
)

profiles_df["Eye_Color"] = profiles_df.apply(
    lambda row: mode_map.loc[
        (row["Hair_Color"], row["Skin_Color"])
    ] if pd.isna(row["Eye_Color"]) else row["Eye_Color"],
    axis=1
)

profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age
0,P299,James Mason,1968-10-07,fourth floor,red,indigo,orange,191,56
1,P086,Christopher Rodriguez,1978-10-03,second floor,indigo,indigo,green,198,46
2,P022,Misty Ashley,1989-08-10,fourth floor,blue,red,violet,154,36
3,P003,Amanda Brown,1995-10-27,lobby,green,blue,violet,158,29
4,P036,William Jones,1990-02-26,fourth floor,blue,yellow,orange,184,35
...,...,...,...,...,...,...,...,...,...
295,P218,Shannon Abbott,1987-08-14,fourth floor,green,green,blue,182,38
296,P126,Kenneth Watson,1987-01-03,NaN,violet,indigo,red,176,38
297,P203,Donald Anderson,1964-09-26,third floor,yellow,indigo,orange,193,60
298,P273,Harold Watkins,2002-07-12,fourth floor,blue,indigo,red,193,23
299,P233,Karen Lambert,1981-06-27,second floor,red,yellow,orange,169,44


## Q3) Finding the features of the culprit

Now that we have successfully cleaned all of our data, lets begin finding the features of the criminal. Take a moment to look at the **"Witnesses"** table. We don't necessarily want all the statements from every single witness.

**NOTE:** Take a look at the structure of each statement, notice how there are only a few variations of statements from the witnesses.

**TASK 3.1 (5 Points):** Find all witnesses that were near the crime scene
- First load in the Witness.csv file and set it to a variable called "**witness_df**"
- create a new dataframe called **"important_witnesses"** that contains the id and the witness statements of those who were near the scene of the crime
- display the new dataframe when you are finished
- **HINT:** look at the floor which the crime happened on.

In [11]:
# Write your code here
witness_df = pd.read_csv("data/Witness.csv")

important_witnesses = (
    witness_df.merge(
        profiles_df[["ID", "Location_during_crime"]],
        on="ID"
    )
    .query('Location_during_crime == "second floor"')
    [["ID", "Statement"]]
)

important_witnesses

       ID                                          Statement
12   P150  I saw someone with orange hair acting suspicious.
16   P075  I saw someone with orange hair acting suspicious.
20   P058   I saw someone with green eyes acting suspicious.
21   P157  I saw someone who looked 152 cm tall acting su...
36   P139  I saw someone who looked 150 cm tall acting su...
..    ...                                                ...
274  P015  I saw someone with orange hair acting suspicious.
279  P268  I saw someone that looks to be 21 years old ac...
285  P077  I saw someone with orange eyes acting suspicious.
286  P168     I saw someone with red skin acting suspicious.
298  P145  I saw someone with orange eyes acting suspicious.

[62 rows x 2 columns]

**TASK 3.2 (10 Points):** Find every potential eye color that the culprit could have

 - Put all the potential eye colors of the culprit in a list called **"potential_eye_colors"** and display it when you're done. potential_eye_colors should have **no duplicates.**

In [12]:
# Write your code here

potential_eye_colors = sorted(
    important_witnesses["Statement"]
    .str.extract(r"with (\w+) eyes")[0]
    .dropna().unique().tolist()
)

potential_eye_colors

['blue', 'green', 'orange', 'violet']

**TASK 3.3 (5 Points):** Find every potential hair color that the culprit could have

 - Put all the potential hair colors of the culprit in a list called **"potential_hair_colors"** and display it when you're done

In [13]:
# Write your code here

potential_hair_colors = sorted(
    important_witnesses["Statement"]
    .str.extract(r"with (\w+) hair")[0]
    .dropna().unique().tolist()
)

potential_hair_colors

['blue', 'green', 'orange', 'violet']

**TASK 3.4 (5 Points):** Find every potential skin color that the culprit could have

 - Put all the potential skin colors of the culprit in a list called **"potential_skin_colors"** and display it when you're done

In [14]:
# Write your code here

potential_skin_colors = sorted(
    important_witnesses["Statement"]
    .str.extract(r"with (\w+) skin")[0]
    .dropna().unique().tolist()
)

potential_skin_colors

['green', 'orange', 'red']

**TASK 3.5 (10 Points):** Find the potential height of the culprit

 - Put the smallest and largest potential heights of the culprit in the variables called **"smallest_height" & "largest_height"** and display them when you are done

In [15]:
# Write your code here

heights = (
    important_witnesses["Statement"]
    .str.extract(r"(\d+) cm tall")[0]
    .dropna().astype(int)
)

smallest_height = heights.min()
largest_height = heights.max()

print(f"Smallest height: {smallest_height}, Largest height: {largest_height}")

Smallest height: 150, Largest height: 170

**TASK 3.6 (8 Points):** Find the potential age of the culprit

 - Put the smallest and largest potential age of the culprit in the variables called **"smallest_age" & "largest_age"** and display them when you are done

In [16]:
# Write your code here

ages = (
    important_witnesses["Statement"]
    .str.extract(r"(\d+) years old")[0]
    .dropna().astype(int)
)

smallest_age = ages.min()
largest_age = ages.max()

print(f"Smallest age: {smallest_age}, Largest age: {largest_age}")

Smallest age: 21, Largest age: 35

## Q4) Finding who ones the ticket

**TASK 4.1 (2 Points):** Loading final dfs


Load in the **"Zichao's Magic Show.csv"** into a dataframe called **"show_df"** and the **"Interrogation_Statement.csv"** into a dataframe called **"interrogation_df"** respectively and display them when you are done

In [17]:
# Write your code here

show_df = pd.read_csv("data/Zichao_s Magic Show.csv")
interrogation_df = pd.read_csv("data/Interrogation_Statements.csv")

display(show_df)
display(interrogation_df)

       ID  Ticket_Number
0    P132       50269975
1    P056       28120732
2    P250       88051289
3    P197       79545169
4    P012       83521845
..    ...            ...
146  P121       31341288
147  P003       85008158
148  P180       24491860
149  P283       38524355
150  P142        2238676

[151 rows x 2 columns]

                     Name                                          Statement
0          Jennifer Mccoy  Stealing? That's not in my nature at all. I re...
1             Karina Gray  Stealing? That's not in my nature at all. I re...
2          Craig Espinoza  I was busy with my project presentation in ano...
3          Michael Mendez  I had back-to-back exams that day. Stealing Dr...
4           Tara Thompson  I wasn't even on campus that day. Check the at...
..                    ...                                                ...
495         Joshua Savage  Why would I need to steal a marker? I have ple...
496          Adrian Black  I was busy with my project presentation in ano...
497       Brittany Taylor  I was busy with my project presentation in ano...
498        William Miller  I wasn't even on campus that day. Check the at...
499  Christopher Ferguson  Stealing? That's not in my nature at all. I re...

[500 rows x 2 columns]


**TASK 4.2 (8 Points):** Create a column called **Ticket_Color** for the **"show_df"** that displays all the colors of the ticket

Remember that there was a show ticket left at the crime scene, take a second to look through **"show_df"**. Try and find a way to identify how you can find the ticket color from the ticket number.

display the **"show_df"** when you are done

**HINT:** examine the **"interogation_df"**

In [18]:
# Write your code here

def ticket_color(ticket):
    digit_sum = sum(int(d) for d in str(ticket))
    last_digit = digit_sum % 10
    
    if last_digit <= 2:
        return "Blue"
    elif last_digit <= 5:
        return "Red"
    elif last_digit <= 7:
        return "Green"
    else:
        return "Yellow"


show_df["Ticket_color"] = show_df["Ticket_Number"].apply(ticket_color)

show_df

       ID  Ticket_Number Ticket_color
0    P132       50269975          Red
1    P056       28120732          Red
2    P250       88051289         Blue
3    P197       79545169        Green
4    P012       83521845        Green
..    ...            ...          ...
146  P121       31341288         Blue
147  P003       85008158          Red
148  P180       24491860          Red
149  P283       38524355          Red
150  P142        2238676          Red

[151 rows x 3 columns]

## Q5) Finding the culprit

A helpful function might be the "iloc" function. Have a look at: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html

**TASK 5.1(10 Points):** Using all the data compiled from before find a person that matches all the features from the profile

- put the name of the culprit in a variable called **"culprit"**

In [19]:
# Write your code here

possible_suspects = profiles_df[
    profiles_df["Eye_Color"].isin(potential_eye_colors)
    & profiles_df["Hair_Color"].isin(potential_hair_colors)
    & profiles_df["Skin_Color"].isin(potential_skin_colors)
    & profiles_df["Height"].between(smallest_height, largest_height)
    & profiles_df["Age"].between(smallest_age, largest_age)
]

red_tickets = show_df[
    show_df["Ticket_color"] == "Red"
]

suspects = possible_suspects.merge(red_tickets, on="ID")

display(suspects)

culprit = suspects.iloc[0]["Name"]

culprit

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age,Ticket_Number,Ticket_color
0,P202,Ishan Kar,1990-07-12,second floor,orange,green,blue,170,35,36984005,Red

'Ishan Kar'

**TASK 5.2 (2 Points):** Check if your culprit is correct!

interrogate your culprit to see if you got the correct person

In [20]:
# Write your code here

culprit_interr = interrogation_df[
    interrogation_df["Name"] == culprit
]

print(f"Culprit Name: {culprit_interr["Name"]}\nCulprit Statement: {culprit_interr["Statement"]}")

Culprit Name: 468    Ishan Kar
Name: Name, dtype: str
Culprit Statement: 468    Fardina's Markers were just too dang cool :( I...
Name: Statement, dtype: str